### PR TITLE
Export a CommonJS and UMD Module

### PR DESCRIPTION
**Pull request by Dig-Doug**
Adds a [rollup](https://rollupjs.org/guide/en) config that builds the library in multiple formats. Each build format is listed in the package.json so tools can leverage them.

Also updates the iterateHeaders code to be in TS and fixes a few lint errors.

# Update to the original description
Based on the feedback I got for [grpc-web](https://github.com/improbable-eng/grpc-web/pull/276), I've updated this PR to use webpack to generate the UMD module.

### CODE REVIEW

**Comment by Dig-Doug** [comment]
@MarcusLongmuir - It looks like the [travis run](https://travis-ci.org/improbable-eng/js-browser-headers/jobs/449374951#L1199) failed because the browser stack key is invalid.

**Comment by Dig-Doug** [comment]
Friendly ping on this.

@jonnyreeves - Is this something you can review?

**Comment by jonnyreeves** [comment]
@Dig-Doug yep, I can get this moving for you; although I need to get the build working again first - I'll have a crack at that in a separate branch.

**Comment by jonny-improbable** [comment]
https://github.com/improbable-eng/js-browser-headers/pull/19 has now been merged, could you merge/rebase your changes @Dig-Doug?

**Comment by Dig-Doug** [comment]
Rebased. Thanks for taking a look!

**Comment by Dig-Doug** [comment]
@jonnyreeves - Can you publish a new version of browser-headers on npm with this change?

**Comment by jonnyreeves** [comment]
@Dig-Doug done, https://www.npmjs.com/package/browser-headers/v/0.4.1

**Pull request merged**
